class SkillsDefs:

    @staticmethod
    def skillsDefs(SKILL_DEF):
        skilldefs = {"SKILL_ALCHEMY" : 0,
            "SKILL_ANATOMY" : 1,
            "SKILL_ANIMALLORE" : 2,
            "SKILL_ITEMID" : 3,
            "SKILL_ARMSLORE" : 4,
            "SKILL_PARRYING" : 5,
            "SKILL_BEGGING" : 6,
            "SKILL_BLACKSMITH" : 7,
            "SKILL_BOWCRAFT" : 8,
            "SKILL_PEACEMAKING" : 9,
            "SKILL_CAMPING" : 10,
            "SKILL_CARPENTRY" : 11,
            "SKILL_CARTOGRAPHY" : 12,
            "SKILL_COOKING" : 13,
            "SKILL_DETECTHIDDEN" : 14,
            "SKILL_ENTICEMENT" : 15,
            "SKILL_EVALINT" : 16,
            "SKILL_HEALING" : 17,
            "SKILL_FISHING" : 18,
            "SKILL_FORENSICS" : 19,
            "SKILL_HERDING" : 20,
            "SKILL_HIDING" : 21,
            "SKILL_PROVOCATION" : 22,
            "SKILL_INSCRIPTION" : 23,
            "SKILL_LOCKPICK" : 24,
            "SKILL_MAGERY" : 25,
            "SKILL_MAGICRESIST" : 26,
            "SKILL_TACTICS" : 27,
            "SKILL_SNOOPING" : 28,
            "SKILL_MUSICIANSHIP" : 29,
            "SKILL_POISONING" : 30,
            "SKILL_ARCHERY" : 31,
            "SKILL_SPIRITSPEAK" : 32,
            "SKILL_STEALING" : 33,
            "SKILL_TAILORING" : 34,
            "SKILL_TAMING" : 35,
            "SKILL_TASTEID" : 36,
            "SKILL_TINKERING" : 37,
            "SKILL_TRACKING" : 38,
            "SKILL_VET" : 39,
            "SKILL_SWORDSMANSHIP" : 40,
            "SKILL_MACEFIGHTING" : 41,
            "SKILL_FENCING" : 42,
            "SKILL_WRESTLING" : 43,
            "SKILL_LUMBERJACK" : 44,
            "SKILL_MINING" : 45,
            "SKILL_MEDITATION" : 46,
            "SKILL_STEALTH" : 47,
            "SKILL_REMOVETRAP" : 48,
            "SKILL_NECROMANCY" : 49,
            "SKILL_FOCUS" : 50,
            "SKILL_CHIVALRY" : 51,
            "SKILL_BUSHIDO" : 52,
            "SKILL_NINJITSU" : 53,
            "SKILL_SPELLWEAVING" : 54,
            "SKILL_MYSTICISM" : 55,
            "SKILL_IMBUING" : 56,
            "SKILL_THROWING" : 57,
            "SKILL_ALLSKILLS" : 58
            }
        return skilldefs[SKILL_DEF]

    @staticmethod
    def skillsDefsFlags(SKILL_DEF_FLAG):    
        skillsDefsFlags =  {
            "SKILL_FLAG_DISABLED" : b'0x000',
            "SKILL_FLAG_FIGHT" : b'0x001',
            "SKILL_FLAG_MAGIC" : b'0x002',
            "SKILL_FLAG_CRAFT" : b'0x004',
            "SKILL_FLAG_IM_MOBILE" : b'0x008',
            "SKILL_FLAG_SELECTABLE" : b'0x010',
            "SKILL_FLAG_NO_MIN_DIST" : b'0x020',
            "SKILL_FLAG_NO_ANIM" : b'0x040',
            "SKILL_FLAG_NO_SFX" : b'0x080',
            "SKILL_FLAG_RANGED" : b'0x100',
            "SKILL_FLAG_GATHER" : b'0x200',
            "SKILL_FLAG_SCRIPTED" : b'0x300'
            }

        return skillsDefsFlags[SKILL_DEF_FLAG]